apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${STUDENT_ID}-caj-${APP_NAME}
spec:
  destination:
    name: ''
    namespace: ${STUDENT_ID}
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/charts/spring-boot-caj-app
    repoURL: 'https://github.com/kairen/caj-config'
    targetRevision: dev
    helm:
      parameters:
        - name: studenID
          value: ${STUDENT_ID}
        - name: version
          value: v1
      valueFiles:
        - ${APP_NAME}-values.yaml
  project: student
