kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterFileUrl":"http://caj-gateway-speaker01.apps.penguin.rhtw.kubedev.org","fareUrl":"http://caj-gateway-speaker01.apps.penguin.rhtw.kubedev.org","scheduleUrl":"http://caj-gateway-speaker01.apps.penguin.rhtw.kubedev.org"}